### ISSUE TITLE
Issue when attempting to start generator.py

### ISSUE THREAD

**Issue by darkangelvenom** [Matix-Media/discord-alt-token-generator#1]
Microsoft Windows [Version 10.0.18363.836]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\******>cd Desktop

C:\Users\******\Desktop>CD "Token Gen"

C:\Users\******\Desktop\Token Gen>CD discord-alt-token-generator-master

C:\Users\******\Desktop\Token Gen\discord-alt-token-generator-master>venv\Scripts\activate

(venv) C:\Users\******\Desktop\Token Gen\discord-alt-token-generator-master>generator.py help
Traceback (most recent call last):
  File "C:\Users\******\Desktop\Token Gen\discord-alt-token-generator-master\generator.py", line 5, in <module>
    from DiscordAccount import DiscordAccount
  File "C:\Users\******\Desktop\Token Gen\discord-alt-token-generator-master\DiscordAccount.py", line 1, in <module>
    from random_username.generate import generate_username
ModuleNotFoundError: No module named 'random_username'

(venv) C:\Users\******\Desktop\Token Gen\discord-alt-token-generator-master>

**Comment by Matix-Media** [comment]
hi, can you try to just add a little `py` in front of the execution of the generator.py?

**Comment by darkangelvenom** [comment]
This issue has been resolved, i just had to move a few files around, current problem is this:


(venv) C:\Users\ebens\Desktop\Token Gen\discord-alt-token-generator-master>generator.py 10 ebens
Setup...

DevTools listening on ws://127.0.0.1:55445/devtools/browser/7d811ece-ba96-4f55-a4bd-86e7c6f481e6
[10188:2452:0520/170749.654:ERROR:browser_switcher_service.cc(238)] XXX Init()
Bot initialized

Starting loop...

Traceback (most recent call last):
  File "C:\Users\ebens\Desktop\Token Gen\discord-alt-token-generator-master\generator.py", line 222, in <module>
    account = current_bot.generate_token()
  File "C:\Users\ebens\Desktop\Token Gen\discord-alt-token-generator-master\generator.py", line 41, in generate_token
    account = self.register_account()
  File "C:\Users\ebens\Desktop\Token Gen\discord-alt-token-generator-master\generator.py", line 123, in register_account
    self.terms_selector)[0]
IndexError: list index out of range

**Comment by Matix-Media** [comment]
yeah, I already got an report to that issue. I am gonna fix it tomorrow. thanks for the feedback 👍

**Comment by darkangelvenom** [comment]
Awesome! Thanks!

**Comment by Matix-Media** [comment]
Ok, so, its seems like the bot is not able to locate the button to allow the terms of service. idk if this box is available in every country. I live in Europe, and you have to have this box on your page, but if you are living in usa, idk if this is required. Can you tell me if there is a checkbox on the registration page wich you have to select in order to create an account?

Example (in German):
https://i.imgur.com/py1WmFo.png

**Comment by darkangelvenom** [comment]
![Capture](https://user-images.githubusercontent.com/11222717/82614483-98888800-9b8d-11ea-9405-1776bdcbfc32.PNG)
No, I don't think in the US we have that.

**Comment by Matix-Media** [comment]
yeah. there is the problem. the bot is looking for the checkbox but it doesn't exist. I am going to fix this. what you can do right now to let it work for you, remove all lines in the code in the generator.py file which contains the variable terms_checkbox (Line 122-123 & 130). try this and I'd this doesn't work, then let me know 👍

**Comment by darkangelvenom** [comment]
(venv) C:\Users\ebens\Desktop\Token Gen\discord-alt-token-generator-master>generator.py 10 ebens
Setup...

DevTools listening on ws://127.0.0.1:53112/devtools/browser/d2e35512-7332-4c9a-8235-da6893d2bebe
[13196:4916:0521/182814.276:ERROR:browser_switcher_service.cc(238)] XXX Init()
Bot initialized

Starting loop...

Traceback (most recent call last):
  File "C:\Users\ebens\Desktop\Token Gen\discord-alt-token-generator-master\generator.py", line 219, in <module>
    account = current_bot.generate_token()
  File "C:\Users\ebens\Desktop\Token Gen\discord-alt-token-generator-master\generator.py", line 41, in generate_token
    account = self.register_account()
  File "C:\Users\ebens\Desktop\Token Gen\discord-alt-token-generator-master\generator.py", line 122, in register_account
    next_button = self.driver.find_elements_by_css_selector(self.register_next_selector)[0]
IndexError: list index out of range

(venv) C:\Users\ebens\Desktop\Token Gen\discord-alt-token-generator-master>


removed the lines you said and i get the same list index out of range error just with a different line

**Comment by Matix-Media** [comment]
ok, can you tell me, wich css selector the Next button on the register page has. You can find the selector by selecting the button in the inspector, then make a rightclick on the button element in the inspector and copy the Selector. Here is a video explenation:
https://youtu.be/BM1Q9AaD3L4

**Comment by darkangelvenom** [comment]
#app-mount > div.app-1q1i1E > div > div.leftSplit-1qOwnR > div > form > div > div.block-egJnc0.marginTop20-3TxNs6 > div:nth-child(4) > button 

Is this what you are looking for?

**Comment by Matix-Media** [comment]
Yeah! I updated the github repo. You can download it now again and try again. If it doesn't work, just text me.

**Comment by darkangelvenom** [comment]
Problem solved! Only issue now is the checkbox thing so I just removed that by myself. Other suggestions I have is from personal experience of mass making tokens by hand is to either have them create a server and then type something in it before grabbing the token. If you don't do this, sometimes your accounts start getting the "needs to be phone verified message." So if that was a feature you could add on down the line, that might help.

**Comment by darkangelvenom** [comment]
So having run it, it generates tokens perfectly, it just get's picked up by Discord's misuse policies and requires the accounts to be verified by phone.

Edit: One feature that could be useful is being able to add a discord invite in the startup (generator.py 10 user https://discord.gg/YOURSERVERHERE) and have it auto join and post a message in the chat to help bypass discord.

**Comment by Matix-Media** [comment]
yeah. good idea. I am going to to that. I also have plans to add proxy support

**Comment by Matix-Media** [comment]
The new feature with the server joining and message writing is now implemented. I am going to upload it to github now.

**Comment by Name277** [comment]
I have the same issue but I do have the checkbox about the terms and agreements.

this is the error when I run py generator.py: https://pastebin.com/bWmACBLc
Thanks.

**Comment by Name277** [comment]
I managed to fix it, I reinstalled python, reinstalled all the modules, the module "wheel" and I had to install another module called "random-username"
