### ISSUE TITLE
Verification Issues

### ISSUE THREAD

**Issue by Name277** [Matix-Media/discord-alt-token-generator#5]
I'm having problems when I am using the tool under a vpn (tried without vpn as well):

1. the captcha authentication is there a way to skip the captcha, it always appears and it doesn't skip it, I am using the windows username, (name from the C drive).

I get this in cmd: https://pastebin.com/kX86cPp7

2. after the captcha authentication when the account is created it asks me only for a phone number authentication and the tool glitches a bit there as it can't log out.

and for some reason it displays the tokens on cmd but it doesn't write them in the text file but that is likely linked to the problems above, thanks.

**Comment by Matix-Media** [comment]
Hi, the bot can handle phone verification. It should log out automatically.
Also, the bot is writing the token to the file, after the complete. By that I mean, after bot completed all actions for the one token, including writing a message to a server.

Also, I dont know why, but it seems like you chrome driver is not correctly installed if it says that there is a Adapter failure.

There is no way as far as i know to bypass the captcha. I try my best by cerating a custom chrome profile but I can not tell discord to dont give me a captcha.

**Comment by Name277** [comment]
my chromedriver is working by what I can see I do have the extenision and when I run chromedriver.exe it says crhomedriver was started successfully. I also got something else everytime I create an account there is a popup that says Create your first server it looks like this: 

![Capture](https://user-images.githubusercontent.com/65073586/83523696-77ebf680-a4da-11ea-8d80-7944c29548bd.PNG)

and it blocks it as it restarts the bot and it eventually just displays an error

this is kind of an enhancement as I don't know how to make some sort of a html directory on python like the other ones on the generator.py

**Comment by Matix-Media** [comment]
Wired i dont get this popup. Can you send me the HTML tag of the popup?

**Comment by Name277** [comment]
sorry, I am not good with html and website stuff. How do I copy the html code? I'm on google chrome

**Comment by Name277** [comment]
this maybe?: https://pastebin.com/0k11VKV8

**Comment by Name277** [comment]
The main problem I want fixed is the popup as it blocks me completely from running the script correctly,

for the error I got about selenium I found this reddit post here: https://www.reddit.com/r/selenium/comments/fxu2q3/suddenly_getting_odd_chromedriverselenium_errors/

Now without vpn everything works, but when I use a vpn it gives me that error.
